[package]
name = "ts_lib"
version = "0.1.0"
edition = "2021"
description = "A collection of functions I find useful for my projects"
repository = "https://github.com/ThomasSaunders/TS_Lib"
license = "GPL-3"
homepage = "https://github.com/ThomasSaunders/TS_Lib"
readme = "readme.md"

[dependencies]
